### ISSUE TITLE
ls-lint with lint-staged, the global code is executed

### ISSUE THREAD

**Issue by mochalhui** [loeffel-io/ls-lint#135]
```
// .lintsatgedrc.json

{
  "*" : ["ls-lint"]
}

{
ls: 

  .ts: camelCase | snake_case



ignore:
  - .git
  - node_modules
 }
```

**Comment by loeffel-io** [comment]
There is currently no support for lint-staged

**Comment by Igorkowalski94** [comment]
As an alternative, you can use [eslint-plugin-project-structure](https://github.com/Igorkowalski94/eslint-plugin-project-structure), you will have eslint errors in real time.

features:
✅ Validation of project structure (Any files/folders outside the structure will be considered an error).
✅ Validation of folder and file names.
✅ Name case validation.
✅ Name regex validation.
✅ File extension validation (Support for all extensions).
✅ Inheriting the parent's name (The child inherits the name of the folder in which it is located).
✅ Folder recursion (You can nest a given folder structure recursively).
✅ Forcing a nested/flat structure for a given folder.

**Comment by loeffel-io** [comment]
This feature is now available in the `v2.3.0-beta.1` release. 
Please test it and let me know if there are any issues ❤️ 

The upcoming v2.3.0 blog post: https://ls-lint.org/blog/announcements/v2.3.0.html
The docs: https://ls-lint.org/2.3/getting-started/introduction.html
The release notes: https://github.com/loeffel-io/ls-lint/releases/tag/v2.3.0-beta.1

**Comment by romanstetsyk** [comment]
@loeffel-io, I use `ls-lint@v2.2.3` as a command in `lint-staged`, and it works, but it lints all the files. After upgrading to `v2.3.0-beta.1`, it no longer throws errors from `lint-staged`, but it works fine if I run it as `npm run lint:ls`

`lint-staged.config.js`:
```js
export default {
  '*': 'ls-lint',
};

```

`package.json`:
```json
"scripts": {
  "prepare": "husky",
  "lint:ls": "ls-lint"
},
```

**Comment by unrevised6419** [comment]
@romanstetsyk seems to be because the process does not exist with a non zero status.

https://github.com/loeffel-io/ls-lint/pull/215/files#r2029834789
