### ISSUE TITLE
regression: open .ls-lint.yaml: no such file or directory

### ISSUE THREAD

**Issue by johnowennixon** [loeffel-io/ls-lint#163]
After upgrading to ls-lint@2.2.0, ls-lint reports:

open .ls-lint.yaml: no such file or directory

If I rename .ls-lint.yml to .ls-lint.yaml (with an A), it works as before.

But all your documentation says to use .ls-lint.yml.

**Comment by loeffel-io** [comment]
Hey @johnowennixon,

thanks for the report! 

can you please share your directory tree and your command? I will take a look rn

**Comment by loeffel-io** [comment]
On my side 

```bash
bazel run //cmd/ls_lint:ls-lint -- --config ${PWD}/.ls-lint.yml --workdir ${PWD}
```

works as well 

```bash
bazel run //cmd/ls_lint:ls-lint -- --config ${PWD}/.ls-lint.yaml --workdir ${PWD}
```

**Comment by johnowennixon** [comment]
I am just running: ./node_modules/.bin/ls-lint
Or alternatively: ls-lint (in an npm script)
I am not using --config at all.
All packages are updated to latest versions.

**Comment by loeffel-io** [comment]
You are absolutely right! Thank you very much for the report 
The fix should be online in less then 24 hours

**Comment by loeffel-io** [comment]
v2.2.1 fixes this issue
