### ISSUE TITLE
Feature proposal: support for mixed kebab and point case

### ISSUE THREAD

**Issue by alextosic** [loeffel-io/ls-lint#177]
Hello,

Considering both Angular and NestJS use the same file naming conventions (names separated by dashes, separated from the type by dots, e.g. user-session.service.ts), it would be great to have in-built support for this, either by adjusting the existing point.case to allow dashes in the name part of the file name, or adding a new case.

Thanks

**Comment by loeffel-io** [comment]
Hey @alextosic,

you can use sub-extensions for this: 

```
.service.ts: kebab-case
```

more info: https://ls-lint.org/2.2/configuration/the-basics.html#extensions-sub-extensions

**Comment by alextosic** [comment]
Sure, but there's too much possible variations to cover. It can be .module.ts, .component.ts, .constants.ts, .enums.ts, .service.ts, etc.

**Comment by loeffel-io** [comment]
This feature is now available in the `v2.3.0-beta.1` release. 
Please test it and let me know if there are any issues ❤️ 

The upcoming v2.3.0 blog post: https://ls-lint.org/blog/announcements/v2.3.0.html
The docs: https://ls-lint.org/2.3/getting-started/introduction.html
The release notes: https://github.com/loeffel-io/ls-lint/releases/tag/v2.3.0-beta.1
