### ISSUE TITLE
Lint list of dirs/files

### ISSUE THREAD

**Issue by bizob2828** [loeffel-io/ls-lint#18]
I want to introduce this into our team's repo but it will be very disruptive to report all the inconistency failures.  I want to leverage husky and lint-staged.  Not sure if you've thought through this type of support or how to do it

**Comment by loeffel-io** [comment]
Not sure if i got your question right, but vant uses ls-lint in combination with lint-staged and husky here: https://github.com/youzan/vant/blob/dev/package.json#L26

**Comment by bizob2828** [comment]
Sorry if I was unclear. What I meant was it’s not running ls-lint on only the changes files but the entire repository

**Comment by loeffel-io** [comment]
Got it, this is currently not planed - maybe i will add this later

**Comment by bizob2828** [comment]
@loeffel-io would you be open to a PR on this if I do it? I don't want to invest time if it will just be rejected

**Comment by loeffel-io** [comment]
@bizob2828 depends on how you want to resolve the issue (like a concept)

fyi: PRs are always welcome

**Comment by tal-rofe** [comment]
@bizob2828 

Is there any progress with this?

**Comment by loeffel-io** [comment]
@tal-rofe yes! there is now a `warn` option: https://ls-lint.org/1.x/configuration/the-options.html#overview

**Comment by tal-rofe** [comment]
> @tal-rofe yes! there is now a `warn` option: https://ls-lint.org/1.x/configuration/the-options.html#overview

What? I asked about lint-staged

**Comment by loeffel-io** [comment]
My fault, this is not supported yet

**Comment by loeffel-io** [comment]
But you can start migrating your project now more easily with the `warn` option
