### ISSUE TITLE
exit 0 on errors?

### ISSUE THREAD

**Issue by james2doyle** [loeffel-io/ls-lint#19]
Most linters will exit 0 if there are errors or at least have a flag to do that. Is that something you are interested in adding?

The reason being, right now, if this was in a CI pipeline it would just print the output and not actually cause fail. You could wrap up the command and test the output, but that seems excessive. Thoughts?

**Comment by loeffel-io** [comment]
Hey @james2doyle, 

ls-lint throws an exit `1` if there is any lint error, exit `0` if there isn`t any lint error:

- 0: https://github.com/loeffel-io/ls-lint/blob/master/main.go#L67
- 1: https://github.com/loeffel-io/ls-lint/blob/master/main.go#L81

**Comment by james2doyle** [comment]
My bad. I missed that. Must be something screwed up in my environment

**Comment by loeffel-io** [comment]
you could try `set -e`
