### ISSUE TITLE
Custom pattern: kebabcase + pointcase

### ISSUE THREAD

**Issue by pawelczak** [loeffel-io/ls-lint#20]
Hey great tool, keep up the good work!

In our project, we use a specific convention for naming files. We combined kebabcase and pointcase, so files are named like user-list.component.ts. Is it possible for ls-lint to check for this pattern?

**Comment by loeffel-io** [comment]
Hey @pawelczak, 

thank you! 

You simply can use sub extensions: 

```yaml
.component.ts: kebab-case
```

Another solution could be the `regex` rule

**Comment by loeffel-io** [comment]
Issue solved @pawelczak?
