### ISSUE TITLE
Option to output a report in JSON format

### ISSUE THREAD

**Issue by BioPhoton** [loeffel-io/ls-lint#203]
Very nice lib!!! 

It would be really useful to be able to pass an argument to produce a json report.

**Comment by loeffel-io** [comment]
Thanks! I think this belongs somehow to #187

**Comment by loeffel-io** [comment]
This feature is now available in the `v2.3.0-beta.1` release. 
Please test it and let me know if there are any issues ❤️ 

The upcoming v2.3.0 blog post: https://ls-lint.org/blog/announcements/v2.3.0.html
The docs: https://ls-lint.org/2.3/getting-started/introduction.html
The release notes: https://github.com/loeffel-io/ls-lint/releases/tag/v2.3.0-beta.1
