### ISSUE TITLE
Windows: Inconsistent slash matching

### ISSUE THREAD

**Issue by MiroslavPetrik** [loeffel-io/ls-lint#21]
Hi, first of all thanks for the tool, simple, fast, superb!

I found issue with using it on windows.

Given config:
```
ls:
  src/**/*:
    .dir: kebab-case | snake_case
ignore:
  - src/@types
  - src/atoms/dashboard-table
```

The result is:
```
>ls-lint
2020/04/20 11:40:42 .\src\@types failed for rules: kebabcase | snakecase
2020/04/20 11:40:42 .\src\atoms\dashboard-table\local-atoms\CustomDate failed for rules: kebabcase | snakecase
2020/04/20 11:40:42 .\src\atoms\dashboard-table\local-atoms\DaysOfAdmissionTag failed for rules: kebabcase | snakecase
2020/04/20 11:40:42 .\src\atoms\dashboard-table\local-atoms\Flag failed for rules: kebabcase | snakecase
2020/04/20 11:40:42 .\src\atoms\dashboard-table\local-atoms\ObraCheckboxes failed for rules: kebabcase | snakecase
```

I think this is strange, because obviously the `ls` part works on windows with slash `/` but the ignore part does not (which is correct as the docs mention you should use backslash on windows)

So now I fixed the ignore part to have backslash pattern for windows.
```
ls:
  src/**/*:
    .dir: kebab-case | snake_case
ignore:
  - src/@types
  - src\@types
  - src/atoms/dashboard-table
  - src\atoms\dashboard-table
```

But I don't like the inconsistency that the `ls` part works while the `ignore` does not.

To fix this, the tool should handle the original config so it works properly on Widnows to get better user experience.

**Comment by loeffel-io** [comment]
Thank you for your issue!

First of all: you want to use it on windows and linux/mac?

**Comment by MiroslavPetrik** [comment]
Yes, I have it in a project where the devs have both win & unix systems.

**Comment by loeffel-io** [comment]
Alright

FYI: The `ls` part works, cause [doublestar](https://github.com/bmatcuk/doublestar) supports this for the glob patterns (like `*` or `**`). For a normal `ls` definition, this should not work.

For now, i could implement a `--file` solution like: (in case there _could_ be more operating systems which use backslashes or some other sep char)

`ls-lint --file=".ls-lint-windows.yml"` for your windows machines. 

What do you think?

**Comment by MiroslavPetrik** [comment]
I don't want to maintain 2 files with the same set of rules.
I would expect the lib to handle the input in same way on each OS properly.

E.g. I don't have `.gitignore-windows` yet the same `.gitignore` works on macs and windowses.

**Comment by loeffel-io** [comment]
I agree

Try to add this feature soon

**Comment by harrytran998** [comment]
@loeffel-io Hey bro, could I ask you what your progress in this feature? My team use both MacOs & Windown, so I can't use it on the project. Hope you fix it!

**Comment by loeffel-io** [comment]
Hey @harrytran998 @MiroslavPetrik , 

i took a look - i think just changing the current path seperator to the unix path seperator should do the trick (just one line). https://github.com/loeffel-io/ls-lint/blob/master/config.go#L16 

This will have some breaking changes for the window environments (must change from backslash to slash) but i could release this in a new major version. 

I currently have no access to a windows machine - someone have to test this before the release. 
Maybe @pustovalov? 

Could provide a final windows test binary tomorrow

**Comment by pustovalov** [comment]
Hey @loeffel-io,

I can check in a couple of hours

**Comment by loeffel-io** [comment]
@pustovalov thanks! ❤️ 

Already working on it

**Comment by loeffel-io** [comment]
This should do the trick: 
[ls-lint-v1.9.0-beta1.zip](https://github.com/loeffel-io/ls-lint/files/4845496/ls-lint-v1.9.0-beta1.zip) (includes linux, macos and windows binaries)

Would love to see some tests on Windows machines (also some regex rule tests would be awesome, but i added some unit tests for this). ❤️ 

More informations: https://github.com/loeffel-io/ls-lint/tree/feature/loeffel/path-separator-inconsistency#major-changes

**Comment by pustovalov** [comment]
source:
https://github.com/pustovalov/ls-lint/tree/windows-check

config:
```
ls:
  packages/*/{src,__tests__}:
    .js: kebab-case
    .ts: camelCase | PascalCase
    .d.ts: camelCase
    .spec.ts: camelCase | PascalCase
    .mock.ts: camelCase
ignore:
  - packages/compiler-core/src/@types
```

1.8.1:
```
PS C:\Users\Pavel-PC\Downloads\vue-next-master>  yarn ls-lint
yarn run v1.19.1
$ ls-lint
2020/06/29 15:32:55 .\packages\compiler-core\src\@types\validate_expression.ts failed for rules: camelcase | pascalcase
error Command failed with exit code 1.
```

https://github.com/pustovalov/ls-lint/tree/windows-check
https://yarnpkg.com/package/pustovalov-ls-lint - 0.0.9

```
PS C:\Users\Pavel-PC\Downloads\vue-next-master>  yarn ls-lint
yarn run v1.19.1
$ ls-lint
Done in 1.44s.
```

**Comment by pustovalov** [comment]
@loeffel-io you can also release a beta version of package to the registry in feature:

Like I use for this package:
https://yarnpkg.com/package/talkable-ui-kit


```
yarn publish --tag beta
```
https://classic.yarnpkg.com/en/docs/cli/publish#toc-yarn-publish-tag

**Comment by loeffel-io** [comment]
Thank you so much! 

So the last log from [comment](https://github.com/loeffel-io/ls-lint/issues/21#issuecomment-651094535) is the `v1.9.0` one?

**Comment by pustovalov** [comment]
almost, I compiled your branch and published to the registry like `0.0.9`

**Comment by loeffel-io** [comment]
Alright, so looks like it works right? 

fyi: just published v1.9.0-beta2

**Comment by pustovalov** [comment]
works for me
```
PS C:\Users\Pavel-PC\Downloads\vue-next-master> yarn why @ls-lint/ls-lint
yarn why v1.19.1
[1/4] Why do we have the module "@ls-lint/ls-lint"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@ls-lint/ls-lint@1.9.0-beta2"
info Has been hoisted to "@ls-lint/ls-lint"
info Reasons this module exists
   - "workspace-aggregator-6dd86a56-ec65-418f-97b8-a923f3f3730c" depends on it
   - Specified in "devDependencies"
   - Hoisted from "_project_#@ls-lint#ls-lint"
info Disk size without dependencies: "9.51MB"
info Disk size with unique dependencies: "9.51MB"
info Disk size with transitive dependencies: "9.51MB"
info Number of shared dependencies: 0
Done in 0.56s.
PS C:\Users\Pavel-PC\Downloads\vue-next-master>  yarn ls-lint
yarn run v1.19.1
$ ls-lint
Done in 1.70s.
PS C:\Users\Pavel-PC\Downloads\vue-next-master>
```

**Comment by pustovalov** [comment]
have you added `--tag beta` when released a new version?

```
Tags
latest
1.9.0-beta.4
```

**Comment by loeffel-io** [comment]
thats the thing: tried some formats like `1.9.0-beta2` or `1.9.0-beta.2` - looks like my drone.io [npm plugin](http://plugins.drone.io/drone-plugins/drone-npm/) can't handle beta tags or tags 

so `1.9.0-beta4` is now tagged under latest which is pretty bad

**Comment by pustovalov** [comment]
>looks like my drone.io npm plugin can't handle beta tags or tags overall
looks like you are right

```
~/dev/oss/ls-lint/npm]$ yarn publish --tag beta

0.0.9 - latest
0.0.10 - beta
```
https://www.npmjs.com/package/pustovalov-ls-lint

**Comment by loeffel-io** [comment]
got it - `v1.9.0-beta.5` is now tagged as `beta`

try to unpublish all other versions now 👍

**Comment by loeffel-io** [comment]
Retagged the `v1.8.1` to `latest` 👍

**Comment by loeffel-io** [comment]
Docker tags also fixed 👍

**Comment by loeffel-io** [comment]
I will give @MiroslavPetrik, @harrytran998, .. a chance to test the beta version for the next 24 hours - then i will release the v1.9.0

**Comment by loeffel-io** [comment]
v1.9.0 released 🕺
