### ISSUE TITLE
Cosmiconfig to support shared configuration files

### ISSUE THREAD

**Issue by aegirokran** [loeffel-io/ls-lint#22]
As a developer working on multiple projects,
I want to be able to use shared ls-lint configs,
so that I don't have to copy-paste a `.ls-lint.yml` file in each repo.

It would be great if ls-lint used [Cosmiconfig](https://github.com/davidtheclark/cosmiconfig) to find and load configuration like other formatting/linting tools -

- [prettier's usage](https://github.com/prettier/prettier/search?q=cosmiconfig&unscoped_q=cosmiconfig)
- [stylelint's usage](https://github.com/stylelint/stylelint/search?q=cosmiconfig&unscoped_q=cosmiconfig)

The ideal situation would be to create a shared config package like `lslint-config-myteam` and have that export a config file named `lslint.config.js` that any project could use.

Additionally, having the shared config in JS format instead of YAML format allows for more flexibility to override the shared config if each project has slightly different needs.

**Comment by loeffel-io** [comment]
Hey @aegirokran, 

thank you for your contribution!

I am already working on something like this as mentioned in the [roadmap](https://github.com/loeffel-io/ls-lint#roadmap):

There will be a private and public registry based on [go-saas](https://github.com/go-saas) and [registry](https://github.com/ls-lint/registry). 

JSON Support could be added later 👍  

Cosmiconfig is not an option, cause ls-lint supports all kind of programming languages - ls-lint will handle this the own way

The final solution should look like: 

```
ls-lint publish --name="aegirokran" --token="abc" --tag="v1.2.1"
```

Would this fit your wishes? 

Have a good day!

**Comment by loeffel-io** [comment]
ping @aegirokran 

what do you think about that?

**Comment by brattonross** [comment]
I'm also interested in being able to share config, but also sharing config in a more modular way e.g. through the use of plugins.

The particular use case that I'm thinking is this; I'm the developer of a Vue component library and I want to follow the convention of prefixing my components with a letter e.g. `VComponent`. Out of the box to support this I need to write my own regex -- which admittedly is simple -- but it would be handy if I could instead install a package that I can plug in to my ls-lint config.

I guess then I have the issue of how to customize the prefix or directories that this rule should apply to.

Just a thought, let me know if I'm being too crazy 😁

**Comment by loeffel-io** [comment]
Hey @brattonross, 

thanks for your contribution! 

Thats a good idea but will not that easy to resolve for any programming language. 

Could you give me an example of how you want to use a plugin like this?

**Comment by brattonross** [comment]
I appreciate that it is possibly more complex than it is worth to implement. The first thing that comes to mind is:

```yml
ls: 
    .js: snake_case
    .ts: snake_case | camelCase
    .d.ts: PascalCase
    .html: regex:[a-z0-9]+
    .vue: VueComponent

plugins:
    - ls-lint-plugin-vue-component

ignore:
    - node_modules
```

The listed plugins should be package names of plugins to resolve. These plugins should expose a map of rules such as the ones in `rule.go`. It should then be possible to use those rules in your `ls-lint.yml` file as you would with built in rules.

I guess the complexity is then in how to get this working for various languages. For example in the case of a node project I could make sure that my plugin is installed through npm, then it would be a case of having the ls-lint node cli resolve the package and get the Go plugin file to load.

**Comment by loeffel-io** [comment]
Got it! What about the following solution: 

As mentioned above there will be a `base` option to extend `.ls-lint.yml` files from the registry. 

So your parent/plugin `.ls-lint.yml` could look like: 

```yaml 
ls: 
    ...

rules: # new option
    VueComponent: [a-z0-9]
```

and then your own `.ls-lint.yml` config would look like: 

```yaml 
base:
    - ls-lint/js
    - ls-lint-plugin-vue-component

ls: 
    .vue: VueComponent
```

This could work for any programming language through the registry and the compiler could create new regex rule for any defined rule 

What do you think?

**Comment by brattonross** [comment]
I think being able to define your own rules and reuse them is a great idea, and much less complicated than my suggestion!

**Comment by loeffel-io** [comment]
Nice to hear that! I think this could be a great feature and will be mentioned in the `v2` collecting thread soon

**Comment by aegirokran** [comment]
I can appreciate your dedication to keeping this tool language agnostic.

For my needs, within my organization I have many TypeScript apps. I'd like to use the same `ls-lint` configuration for each project, and have that config be published somewhere private like to an internal npm registry.

It would be nice if `ls-lint` could extend from a shared configuration in JS or even JSON format similar to `eslint` or `tsconfig`.

If this is not within the scope of this linter tool, feel free to close this issue 👍🏼

**Comment by loeffel-io** [comment]
@aegirokran this should be possible

fyi: after 6 months of hard work we just finished the beta of [makeless](https://github.com/makeless) (go-saas => makeless) and we will try to go forward with the registry in the next weeks

**Comment by iceycc** [comment]
Excuse me, ask, has it been realized

**Comment by aegirokran** [comment]
@loeffel-io -
Great to hear this has landed in v2! Would it be possible to get some updates to the documentation (on ls-lint.org) with examples of how to extend from files from the registry.

**Comment by loeffel-io** [comment]
Hey @aegirokran, 

extending the config with `base` is not supported in `v2.0.0` and is planned for a later `v2.x` release. 

But with `v2.0.0` you can use the `config` option to ref to a `.ls-lint.yml` config from a external npm package for example. 

`ls-lint --config node_modules/bla/foo/.ls-lint.yml`

Feel free to ask me anything to get this up and running

**Comment by loeffel-io** [comment]
Just as a reference ([Bazel](https://bazel.build) context)

At my company we have a `rules` repository where the ls-lint macro and config lives:

```starlark
def ls_lint_test(name, config = "@com_github_mindful_hq_rules//pkg/ls_lint:.ls-lint.yml", data = []):
    native.sh_test(
        name = name,
        srcs = ["@com_github_mindful_hq_rules//:ls_lint"],
        data = data + [config],
        args = [
            "--config $(location " + config + ")",
        ],
    )
```

Then we use the macro like this: 

```starlark
load("@com_github_mindful_hq_rules//pkg/ls_lint:ls_lint.bzl", "ls_lint_test")

ls_lint_test(
    name = "ls_lint",
    data = glob([
        "*.bzl",
        "*.bazel",
    ]) + [
        "//deployments/modules:files",
        "//deployments/production:files",
    ],
)
```
