### ISSUE TITLE
readme.md was not published

### ISSUE THREAD

**Issue by aladdin-add** [loeffel-io/ls-lint#24]
![image](https://user-images.githubusercontent.com/13050025/86568709-dd327c00-bf9f-11ea-929c-2d21c29846ed.png)

**Comment by loeffel-io** [comment]
Thanks @aladdin-add for your contribution!
I will fix this in the next release

**Comment by loeffel-io** [comment]
Readme fixed: https://www.npmjs.com/package/@ls-lint/ls-lint
