### ISSUE TITLE
How do you use `pointcase` correctly?

### ISSUE THREAD

**Issue by romanstetsyk** [loeffel-io/ls-lint#257]
With the config file like this:
```
ls:
  .css: point.case
```
The rule in it doesn't match any file that uses point case and ends with `.css`. For example, it won't match `test.point.case.css` because the extension here is `point.case.css`. As a consequence, it won't catch an error if there's a typo, e.g. `test-point.case.css`

**Comment by loeffel-io** [comment]
crazy, it was really unclear for me that this rule still exists. 
This rule needs to be removed.
 Please use sub extensions and wildcard extensions for this.
This rule will be removed in v2.3.0
