### ISSUE TITLE
[Question] Is it possible to limit directory nesting with ls-lint?

### ISSUE THREAD

**Issue by vitalets** [loeffel-io/ls-lint#264]
I'm searching for a tool to limit directory nesting level in my project. Can `ls-lint` solve it?

**Comment by loeffel-io** [comment]
Hey, you can do this in the new beta with `exists:0`.
But there could be still an issue with this needs to be resolved: https://github.com/loeffel-io/ls-lint/issues/249

I close this in case of #249

**Comment by vitalets** [comment]
Hi @loeffel-io ! 
Thanks for pointing on that.
Just to clarify - if I want to restrict nesting in `src` directory up to 3 levels, it will be the following config:
```
ls:
  src/*/*/*/*:
    .dir: exists:0
```

**Comment by loeffel-io** [comment]
Yes, that would be the way for now i think when #249 is fixed

**Comment by vitalets** [comment]
> Yes, that would be the way for now. Should work without #249 but not sure, please test

I've checked, with `v2.3.0-beta.1` it works.
Thank you for that tool!
