### ISSUE TITLE
How to Shorten the multiple lines regex in one line!

### ISSUE THREAD

**Issue by harrytran998** [loeffel-io/ls-lint#34]
Hi the owner, I have a rule like that
```yml
 .vue: regex:^index| regex:^default | regex:^student | regex:^_id | regex:^_slug
```
So I want to do like the normal regex --> Just one line

```yml
.vue: regex:^(index|default|_id|_slug)
```

Thank you bro!

**Comment by loeffel-io** [comment]
Hey @harrytran998 

sorry about your issue, but its currently not possible to handle this with one regex rule - because the OR operator `|` breaks the pattern  

I think the OR operator gets extended in v2 with a ongoing and trailing whitespace - then this should work 👍 

I will keep you updated

**Comment by loeffel-io** [comment]
With v2.x this is provided by the config option: https://github.com/loeffel-io/ls-lint/releases/tag/v2.0.0-beta.0

Feel free to try it out
