### ISSUE TITLE
ignore pattern is not applied to subdirectory

### ISSUE THREAD

**Issue by chuyik** [loeffel-io/ls-lint#35]
The `ignore` pattern is not applied to subdirectory, for example:

```bash
# common monorepo structure

├── node_modules # this folder skips
└── packages
    └── some-package
        └── node_modules # this folder does NOT skip
```

config:
```yml
ignore:
  - node_modules
```

I have to add an ignore pattern like `packages/some-package/node_modules`, but it's still a workaround, not a perfect solution.

**Comment by loeffel-io** [comment]
Hey @chuyik,

thank you for your contribution - as mentioned in the [docs](https://ls-lint.org/1.x/configuration/the-basics.html#using-directory-patterns) there is currently no glob support for the `ignore` part 

Will be added in v2

**Comment by rarkins** [comment]
@loeffel-io FYI it doesn't mention `ignore` specifically where you linked:

![image](https://user-images.githubusercontent.com/6311784/101799707-c5da5a80-3b0c-11eb-8052-c266bfe1229c.png)

**Comment by loeffel-io** [comment]
yeah, you are right - you can apply a pr for this if you are interested: https://github.com/ls-lint/docs
