### ISSUE TITLE
How to disable some specific names?

### ISSUE THREAD

**Issue by basharov** [loeffel-io/ls-lint#39]
I'd like to prohibit using filename `index.css` in my components but cannot find details about the syntax of regex used in the project to build a proper expression.

Please advise.

**Comment by loeffel-io** [comment]
So everything for `.css` should be allowed expect `index.css`?

**Comment by basharov** [comment]
You're right, I want to allow any css filenames except `index.css`

**Comment by loeffel-io** [comment]
https://regex101.com/r/xYtUN5/1 could work

**Comment by basharov** [comment]
@loeffel-io It showd the error:
> error parsing regexp: invalid or unsupported Perl syntax: `(?!`

**Comment by loeffel-io** [comment]
`"Go regex does not support lookarounds."` - thats sad

In this case you have to find a way to convert your lookarounds to std regex

**Comment by loeffel-io** [comment]
just keep in mind that there is the `ignore` pattern: https://ls-lint.org/1.x/configuration/the-basics.html#creating-configuration 
maybe this can help you too

**Comment by loeffel-io** [comment]
@basharov to make it more easy we could provide a `not_regex` rule in `v2` 🤔

**Comment by LaamGinghong** [comment]
I also encountered the same scene. In my scenario, I want all tsx files except for the file name `use***.tsx` to use the pascal case rule, and `use***.tsx` to use the camel case rule. It doesn’t seem to meet my needs so far

**Comment by jfairley** [comment]
@LaamGinghong I keep all of my hooks in a separate directory (`src/hooks`). That way, I can set up a separate rule for my hooks directory.

**Comment by jfairley** [comment]
@loeffel-io I'm here looking for something similar. It would be nice to define reject patterns. `index.css` is one example, but similar, imagine my project is using a postcss library. I would want to forbid all `.css` files. I tried `.css: "regex:"` but empty regex isn't allowed. Admittedly, that's a hack anyway.

In my specific case, I'm trying to target inconsistent naming between `.types.ts` and `.type.ts`. I want to blacklist one of those.

**Comment by ccoVeille** [comment]
For anyone interested. You can now use `exists:0` as a rule. Please check the documentation

**Comment by loeffel-io** [comment]
@ccoVeille `v2.3.0` is not released yet - there is one single piece that is missing

**Comment by ccoVeille** [comment]
Author opened the issue 3 years ago. I assumed he could wait a few more days/week.

But you are right, it's not yet available or documented

**Comment by loeffel-io** [comment]
As far i can tell this is one of the most challenging tasks for me - its beautiful how wildcard extensions, selected files and exists working together magically

**Comment by loeffel-io** [comment]
This feature is now available in the `v2.3.0-beta.1` release. 
Please test it and let me know if there are any issues ❤️ 

The upcoming v2.3.0 blog post: https://ls-lint.org/blog/announcements/v2.3.0.html
The docs: https://ls-lint.org/2.3/getting-started/introduction.html
The release notes: https://github.com/loeffel-io/ls-lint/releases/tag/v2.3.0-beta.1
