### ISSUE TITLE
How to lint only a list of passed files?

### ISSUE THREAD

**Issue by basharov** [loeffel-io/ls-lint#40]
I use this tool https://github.com/okonet/lint-staged to lint my changed files before committing them.
Only files I changed are linted, so if there are some legacy files that don't meet the rules, they don't get linted and don't break my flow.

Is it possible to make ls-lint work in a similar way - lint only files passed as arguments by lint-staged?

**Comment by loeffel-io** [comment]
currently not, but i will keep that in mind when i will build the `v2`

**Comment by airtonix** [comment]
should label this as desired for v2 so it doesn't get missed. this is fairly critical to ls-lint uptake.

**Comment by ElsaOOo** [comment]
yes, I want to lint my staged files, and this is most needed
