### ISSUE TITLE
Configuration file request.

### ISSUE THREAD

**Issue by lo-corp** [loeffel-io/ls-lint#41]
It doesn't look good when you're forced to use only .yml file extension.

I want to store the config in ls-lint.yaml, and I'm sure some people would like the configs in json format as well. is it possible?

Afaik there're some pre-built tools to enable this behaviour.

https://github.com/search?o=desc&q=config+json+yaml&s=stars&type=Repositories

**Comment by loeffel-io** [comment]
Duplicate of #29 and mentioned in #36
