### ISSUE TITLE
Support for SCREAMING_SNAKE_CASE

### ISSUE THREAD

**Issue by aegirokran** [loeffel-io/ls-lint#44]
In our projects, we tend to add may items to the `ignore` list in the `.ls-lint.yml` config file for common Markdown files. Per industry common practices, these files are named with `SCREAMING_SNAKE_CASE`. For example:

`.ls-lint.yml`
```
ignore:
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - README.md
```

It would be great to not have to add these to the ignore list for many repos. Would it be a possibility to add support for SCREAMING_SNAKE_CASE to ls-lint so that we could configure our projects like:

`.ls-lint.yml`
```
ls:
  .md: SCREAMING_SNAKE_CASE
  ...
```

<img width="400" src="https://user-images.githubusercontent.com/134873/104349632-06384a00-54b8-11eb-8df3-2f715a391183.jpg">

**Comment by loeffel-io** [comment]
Hey @aegirokran, 

great idea - will add this to the `v2` 

Anyone: feel free for a pull request (!)

**Comment by aegirokran** [comment]
Thank you for the acknowledgment. Glad to know that it'd be a welcome addition.

**Comment by loeffel-io** [comment]
Will be part of v1.11.0 🎉
