### ISSUE TITLE
Selectively override rules for inner directories

### ISSUE THREAD

**Issue by brunomperes** [loeffel-io/ls-lint#45]
First of all, thanks for the great plugin!

I see in the docs that having a directory config causes it to override all rules for the inner directories:

![Screenshot 2021-02-08 at 16 13 29](https://user-images.githubusercontent.com/1819575/107238876-966e9e00-6a28-11eb-99fc-536c859a7fce.png)

I think most of consumers imagine the rules to work like `.gitignore`, so adding a rule for certain extension should automatically nest and only override if explicitly setting another rule for that directory.

Given that I believe this is rather unwanted and as such could you consider adding to V2 #36  ?

*Looking forward to V2!* 😃

**Comment by loeffel-io** [comment]
Hey @brunomperes, 

thank you for your question and suggestion, but thats the design of ls-lint and "wanted".

The reason for this is that - in our opinion - a project should have a strict definition on where your specific files life.

Example: 

`components` directory should just include components like `.vue` files and maybe some `.js` or `.ts` tests - they could include some subdirectories but they should always belongs to the same point of architecture => components 

Have a good day!

**Comment by cbdeveloper** [comment]
I was looking for something like this as well.

For example:

```
ui.parts/
  SomeReactComponentA/
  SomeReactComponentB/
```

It would be nice to do something like:

```
ls:
  src/**/ui.parts:
    .subDir: PascalCase
```

**Comment by loeffel-io** [comment]
👍 i understand your need and i will evaluate that

**Comment by m-shaka** [comment]
@loeffel-io Hi. `ls-lint` is helping us a lot.

I have another use case of that. Remix's file base routing requires a directory structure like this
![image](https://github.com/loeffel-io/ls-lint/assets/12842076/47798644-c461-46f3-bd54-321ca5549bb3)
https://remix.run/docs/en/main/file-conventions/routes#folders-for-organization

**Comment by loeffel-io** [comment]
> I was looking for something like this as well.
> 
> For example:
> 
> ```
> ui.parts/
>   SomeReactComponentA/
>   SomeReactComponentB/
> ```
> 
> It would be nice to do something like:
> 
> ```
> ls:
>   src/**/ui.parts:
>     .subDir: PascalCase
> ```

This is already supported - you can simple do something like this: 

```
ls:
  src/**/ui.parts:
    .subDir: PascalCase
    
    '**':
        .dir: PascalCase
```

I will add this to the docs for v2.3.0

**Comment by loeffel-io** [comment]
> @loeffel-io Hi. `ls-lint` is helping us a lot.
> 
> I have another use case of that. Remix's file base routing requires a directory structure like this ![image](https://private-user-images.githubusercontent.com/12842076/343721156-47798644-c461-46f3-bd54-321ca5549bb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTcxNDgsIm5iZiI6MTcyMDUxNjg0OCwicGF0aCI6Ii8xMjg0MjA3Ni8zNDM3MjExNTYtNDc3OTg2NDQtYzQ2MS00NmYzLWJkNTQtMzIxY2E1NTQ5YmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA5MjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhOGY1ZjBlZTExMWY3YjFlYTkwODlhZTIyNTMwOWFhMWY4NGI5ZmZhOTEwOTVkZjdhNTc4NzYzNzVhNzBlZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HfcPTe73h14DFVlEKgcLXnTJNUeNjMdaMBVMNbLP3e8) https://remix.run/docs/en/main/file-conventions/routes#folders-for-organization

Thats a simple one @m-shaka 

```
ls:
  routes/*:
    .dir: regex:_[a-z]+\._*[a-z]+ # something like this (https://regex101.com/r/QbF30g/1)
    .ts: kebab-case 
    .tsx: kebab-case
    .server.ts: kebab-case
    .jpg: kebab-case
```

**Comment by ccoVeille** [comment]
oh really ? I looked for it yesterday !
