### ISSUE TITLE
One regex for everything

### ISSUE THREAD

**Issue by What1s1ove** [loeffel-io/ls-lint#48]
Hi there 🙂

Maybe I missed something in the documentation, but can I use one `regex` for any files?

![image](https://user-images.githubusercontent.com/42296182/111915729-692dfa80-8a80-11eb-833a-1f25cf180350.png)

Thanks 🙂

**Comment by loeffel-io** [comment]
Hey, that will be supported in v2 #36 (Reusable rules) 👍
