### ISSUE TITLE
Special characters in filename - [id].tsx

### ISSUE THREAD

**Issue by binary64** [loeffel-io/ls-lint#52]
Hi, what would the regex be to allow a file called `[id].tsx` ?

Many thanks

**Comment by loeffel-io** [comment]
Hey @binary64, like this `[\d]+` or `\[id\]` ?

**Comment by binary64** [comment]
Ah this works:
```
.tsx: 'regex:\[\d\]$'
```
for the `[xxxx].tsx` files but not for regular files like `index.tsx`

But this doesn't
```
.tsx: 'regex:\[\d\]$ | kebabcase'
```

**Comment by binary64** [comment]
Working solution:
```
.tsx: 'kebabcase | regex:\[[a-z]*\]$
```
Not sure what I did wrong but it's working now. Thank you.
