### ISSUE TITLE
Installing npm module on M1 CPU fails

### ISSUE THREAD

**Issue by brunomperes** [loeffel-io/ls-lint#58]
After moving to a Macbook with Apple M1 chip the installation of npm package is failing with the following message:

```
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error @ls-lint/ls-lint@1.9.2: The CPU architecture "arm64" is incompatible with this module.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

node's `process.arch` is giving me `'arm64'` , I'm on macOS 11.4 and node v14.17.3.

Any advice? I see there are some [CPU restrictions on the package.json](https://github.com/loeffel-io/ls-lint/blob/master/npm/package.json#L16-L19), but theoretically it should work?

Possibly related issues:
https://github.com/lovell/sharp/issues/2460
https://github.com/gridsome/gridsome/issues/1411

**Comment by loeffel-io** [comment]
Please check out 1.10.0-beta.2
