### ISSUE TITLE
Feature request: File-orientated rules

### ISSUE THREAD

**Issue by binary64** [loeffel-io/ls-lint#69]
Regarding https://github.com/loeffel-io/ls-lint/issues/30#

Could this feature be powerful enough to help me enforce test files for every .tsx no matter my structure?

Because I can imagine a regex solution to check for exists would quickly get complicated to manage. Imagine you have a components directory, and inside it you are going to have a wide variety of organization. On one hand you might have a simple /components/button/index.tsx but for a list you might have sub-components like /components/list/{ index.ts , list-item/index.tsx }

Thinking out loud, but it would be cool to say: "all .tsx files inside of /components should have neighboring .spec.tsx files"

**Comment by Igorkowalski94** [comment]
As an alternative, you can use [eslint-plugin-project-structure](https://github.com/Igorkowalski94/eslint-plugin-project-structure), you will have eslint errors in real time.

features:
✅ Validation of project structure (Any files/folders outside the structure will be considered an error).
✅ Validation of folder and file names.
✅ Name case validation.
✅ Name regex validation.
✅ File extension validation (Support for all extensions).
✅ Inheriting the parent's name (The child inherits the name of the folder in which it is located).
✅ Folder recursion (You can nest a given folder structure recursively).
✅ Forcing a nested/flat structure for a given folder.
