### ISSUE TITLE
Specifying default file type

### ISSUE THREAD

**Issue by binary64** [loeffel-io/ls-lint#70]
Hi is it possible to have a default fallback like

```
ls:
  .: 'regex:$never'
  .txt: 'kebabcase'
```
would only allow files like blahBlah.txt and hello.txt

test.jpg and so on would cause error

at the moment I'm having to specify every file type under the sun to be `'regex:$never'` (which is my little hack to make sure these files do not exist)

**Comment by loeffel-io** [comment]
Hey @binary64,

love the idea but i am not sure how to handle that in combination with directories for now 

will think about that 👍

**Comment by loeffel-io** [comment]
also ref: #223

**Comment by loeffel-io** [comment]
This feature is now available in the `v2.3.0-beta.1` release. 
Please test it and let me know if there are any issues ❤️ 

The upcoming v2.3.0 blog post: https://ls-lint.org/blog/announcements/v2.3.0.html
The docs: https://ls-lint.org/2.3/getting-started/introduction.html
The release notes: https://github.com/loeffel-io/ls-lint/releases/tag/v2.3.0-beta.1
