### ISSUE TITLE
Question: Is it possible to verify a repeated pattern?

### ISSUE THREAD

**Issue by jfairley** [loeffel-io/ls-lint#72]
I just created a NestJS app. Long-story-short, when you use the NestJS CLI tool, you end up with files/directories like so:

```
src/
  role/
    role.module.ts
    role.service.ts
  user/
    user.module.ts
    user.service.ts
```

I'd like to verify that the file root matches its directory name, but I'm not sure if it's possible. 

I would want the linter to reject something like `src/user/users.module.ts`.

Is there a way to lint a pattern like this?

**Comment by jfairley** [comment]
Oh, it looks like I have duplicated https://github.com/loeffel-io/ls-lint/issues/59

**Comment by loeffel-io** [comment]
close in case of duplication
