### ISSUE TITLE
Installation gives an error of architecture ia32

### ISSUE THREAD

**Issue by Leifhaa** [loeffel-io/ls-lint#80]
Hello!

Whenever I'm trying to install ls-lint using the command:
`
npm install latest-version
`

I retrieve the following error:

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @ls-lint/ls-lint@1.11.2: wanted {"os":"darwin,linux,win32","arch":"x64,arm64"} (current: {"os":"win32","arch":"ia32"})
npm ERR! notsup Valid OS:    darwin,linux,win32
npm ERR! notsup Valid Arch:  x64,arm64
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: ia32

Is there any way I'll be able to use ls-lint, or is not computer not capeable of doing so? I'm using a quite new ASUS laptop with the processor: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 2803 Mhz, 4 Core(s), 8 Logical Processor(s)

**Comment by loeffel-io** [comment]
Hello, 

so you running a windows 32-bit system? 

32 bit is not supported

**Comment by Leifhaa** [comment]
Hello, appreciate the response!

No, I'm running x64-based

**Comment by gassims** [comment]
Hi

I'm facing the same issue. One of the dependency packages uses ls-lint as a dependency package and when I run yarn install it shows the same error. Please see screenshot:

![image](https://user-images.githubusercontent.com/45095831/224053657-42612684-f9a8-49a5-b74b-cd99219ad667.png)

### Device Specifications:

Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor

### Windows specifications:
Edition	Windows 10 Home
Version	22H2
Installed on	‎2/‎25/‎2023
OS build	19045.2673
Experience	Windows Feature Experience Pack 120.2212.4190.0
-----------------------------------------

Your help is much appreciated, thanks!

**Comment by Leifhaa** [comment]
Hi

FYI I did not manage to solve this problem myself so I used a virtual machine/docker to solve it. I assume you encountered the issue when working with DHIS2, I also had the problems when working with DHIS2 :)

**Comment by Leifhaa** [comment]
Just a regular winodws 10 OS. I believe it's the CPU architecture which is the problem. In the VM, it's a virtual CPU which is supported by LSLint.

**Comment by gassims** [comment]
@loeffel-io is there any update on this? Thanks!

**Comment by wiget** [comment]
Hello.
If you are affected by this issue, please make sure that you have installed node.js for x64 not x86 architecture.

**Comment by gassims** [comment]
> Hello. If you are affected by this issue, please make sure that you have installed node.js for x64 not x86 architecture.

Yes @wiget, thanks! I checked the downloaded file and it's x86. Reinstalling node.js thanks!

(How did you figure this one out?!! 😁😅🤔 )
