### ISSUE TITLE
How to lint directory names with extensions without using a regex?

### ISSUE THREAD

**Issue by RaisinTen** [loeffel-io/ls-lint#82]
I'm trying to lint the name of iconset directories. I was using snake case for all directory names, so previously my rule was:
```yml
ls:
  .dir: snake_case
```

but now that the project contains `.iconset` directories, I'm forced to use a regex like this:
```yml
ls:
  .dir: snake_case | regex:^[a-z]+(_[a-z]+)*\.iconset$
```
to make sure that the part before `.iconset` is in snake case.

I think it would be great if we can find a way to allow people to lint directory names just like filenames.

**Comment by Igorkowalski94** [comment]
As an alternative, you can use [eslint-plugin-project-structure](https://github.com/Igorkowalski94/eslint-plugin-project-structure), you will have eslint errors in real time.

features:
✅ Validation of project structure (Any files/folders outside the structure will be considered an error).
✅ Validation of folder and file names.
✅ Name case validation.
✅ Name regex validation.
✅ File extension validation (Support for all extensions).
✅ Inheriting the parent's name (The child inherits the name of the folder in which it is located).
✅ Folder recursion (You can nest a given folder structure recursively).
✅ Forcing a nested/flat structure for a given folder.
