### ISSUE TITLE
ls-lint with a config flag

### ISSUE THREAD

**Issue by radvym** [loeffel-io/ls-lint#84]
It would be so great if ls-lint would provide the capability of adding a -c or --config flag and then let the user to choose which .yml file with a custom config he wants to use.
Arent there any plans to implement the -c flag for the future development?

**Comment by Mctalian** [comment]
I had a PR open for this but it got closed.

**Comment by loeffel-io** [comment]
With v2.x this is provided by the config option: https://github.com/loeffel-io/ls-lint/releases/tag/v2.0.0-beta.0

Feel free to try it out

**Comment by loeffel-io** [comment]
Since `v2.2.0` (`v2.2.1`) you can use multiple config files with `--config`
