### ISSUE TITLE
Use shareable configuration (not yml)

### ISSUE THREAD

**Issue by dror-weiss** [loeffel-io/ls-lint#85]
As a project maintainer of many projects, I want to standardize on a single `json` or `js` config file for all of them, each extending the base config.
`yml` doesn't support configuration sharing.

Basically, similar behavior to [eslint](https://eslint.org/docs/latest/extend/shareable-configs).

**Comment by janekkkk** [comment]
You can do this. Check this older issue: https://github.com/loeffel-io/ls-lint/issues/22#issuecomment-1560604105
