### ISSUE TITLE
kebab case with multiple periods

### ISSUE THREAD

**Issue by thescientist13** [loeffel-io/ls-lint#87]
Was curious if there was any suggestion for how to support `kebabcase` with a filename that has extra periods in it?  For example, for tests and Storybook files, or even config files, it would be common to have file names like this
- _my-component.spec.js_
- _my-component.stories.js_
- _something.config.js_

This will fail the default rule for `kebabcase`
```sh
2023/03/20 21:36:29 src/components/my-component.spec.js failed for rules: kebabcase
```

Thanks for any help!

**Comment by loeffel-io** [comment]
Hey @thescientist13 

```
ls:
    .spec.js: kebab-case
    .stories.js: kebab-case
    .config.js: kebab-case
```

**Comment by thescientist13** [comment]
AH, thank you!  That is a lot simpler than what I was trying to attempt with regex 😅
